# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cap_from_camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1028, 679)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 650, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.label_2.setObjectName("label_2")
        self.button_takePhoto = QtWidgets.QPushButton(Dialog)
        self.button_takePhoto.setGeometry(QtCore.QRect(900, 0, 131, 681))
        self.button_takePhoto.setStyleSheet("")
        self.button_takePhoto.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/knomori/Desktop/RaspberryPi_PTZControl_FaceRecognition/PC_END/OriginalUI/照相机.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_takePhoto.setIcon(icon)
        self.button_takePhoto.setIconSize(QtCore.QSize(100, 101))
        self.button_takePhoto.setObjectName("button_takePhoto")
        self.label_showCamera = QtWidgets.QLabel(Dialog)
        self.label_showCamera.setGeometry(QtCore.QRect(0, 0, 901, 676))
        self.label_showCamera.setText("")
        self.label_showCamera.setObjectName("label_showCamera")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "从摄像机导入人脸照片"))
        self.label_2.setText(_translate("Dialog", "提示：点击右侧拍照按钮进行拍照，3～6张即可。程序会自动保存图像"))
