# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1157, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_video = QtWidgets.QLabel(self.centralwidget)
        self.show_video.setGeometry(QtCore.QRect(20, 20, 821, 611))
        self.show_video.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.show_video.setText("")
        self.show_video.setAlignment(QtCore.Qt.AlignCenter)
        self.show_video.setObjectName("show_video")
        self.label_show_status = QtWidgets.QLabel(self.centralwidget)
        self.label_show_status.setGeometry(QtCore.QRect(900, 100, 211, 211))
        self.label_show_status.setText("")
        self.label_show_status.setWordWrap(False)
        self.label_show_status.setObjectName("label_show_status")
        self.label_show_name = QtWidgets.QLabel(self.centralwidget)
        self.label_show_name.setGeometry(QtCore.QRect(880, 370, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_show_name.setFont(font)
        self.label_show_name.setText("")
        self.label_show_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_name.setObjectName("label_show_name")
        self.label_show_id = QtWidgets.QLabel(self.centralwidget)
        self.label_show_id.setGeometry(QtCore.QRect(880, 430, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_show_id.setFont(font)
        self.label_show_id.setText("")
        self.label_show_id.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_id.setObjectName("label_show_id")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(850, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.button_setting = QtWidgets.QPushButton(self.centralwidget)
        self.button_setting.setGeometry(QtCore.QRect(1095, 590, 41, 35))
        self.button_setting.setStatusTip("")
        self.button_setting.setObjectName("button_setting")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "树莓派人脸追踪与识别——树莓派端"))
        self.label.setText(_translate("MainWindow", "识别状态："))
        self.button_setting.setToolTip(_translate("MainWindow", "首选项"))
        self.button_setting.setWhatsThis(_translate("MainWindow", "首选项"))
        self.button_setting.setText(_translate("MainWindow", "..."))
